language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t chriswyc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chriswyc/react-test npm test

after_success:
  - docker build -t chriswyc/multi-client ./client
  - docker build -t chriswyc/multi-nginx ./nginx
  - docker build -t chriswyc/multi-server ./server
  - docker build -t chriswyc/multi-worker ./worker

  #log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to docker hub
  - docker push chriswyc/multi-client
  - docker push chriswyc/multi-nginx
  - docker push chriswyc/multi-server
  - docker push chriswyc/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-423623859539'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY