language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t chriswyc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chriswyc/react-test npm test

after_success:
  - docker build -t chriswyc/multi-client ./client
  - docker build -t chriswyc/multi-nginx ./nginx
  - docker build -t chriswyc/multi-server ./server
  - docker build -t chriswyc/multi-worker ./worker